update vagrant example Vagrantfile

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -42,15 +42,12 @@ settings = YAML.load(DEFAULT_SETTINGS)
 if File.exist?(DEFAULT_YAML_NAME)
     custom_settings = YAML.load_file(DEFAULT_YAML_NAME)
     settings.deep_merge!(custom_settings)
-    puts "Project configuration merged from #{DEFAULT_YAML_NAME}"
-    puts YAML::dump(settings)
 end
 
 Vagrant.configure("2") do |config|
     config.ssh.forward_agent = true
     config.vm.box = "ubuntu/xenial64"
     config.vm.define "appliance"
-
     config.vm.synced_folder ".", "/app/src", type: "rsync", create: true,
         rsync__exclude: "", rsync__auto: false,
         rsync__args: ["--verbose", "--archive", "--delete", "-z", "--links"]
@@ -61,6 +58,12 @@ Vagrant.configure("2") do |config|
     if Vagrant.has_plugin?("vagrant-proxyconf")
         if "#{ENV['http_proxy']}" != ""
             config.proxy.http  = "#{ENV['http_proxy']}"
+        end
+        if "#{ENV['lxd_http_proxy']}" != ""
+            config.proxy.http  = "#{ENV['lxd_http_proxy']}"
+        end
+        if "#{ENV['no_proxy']}" != ""
+            config.proxy.no_proxy  = "#{ENV['no_proxy']}"
         end
     end
 
@@ -111,21 +114,46 @@ Vagrant.configure("2") do |config|
     end
 
     config.vm.provision "shell", privileged:true, inline: <<-SHELL
-        # TODO set hostname workaround, see https://github.com/mitchellh/vagrant/issues/5673
+        # wait for cloud-init to finish, also interferes with pkg installing 
+        if which cloud-init > /dev/null; then 
+            echo -n "waiting for cloud-init finish..."
+            cloud-init status --wait
+        fi        
+
+        # set sensible defaults for language and timezone
+        # set LANG, LANGUAGE, LC_MESSAGES and activate LC_ALL in environment
+        export LC_ALL=#{ENV['LANG']}
+        printf "LANG=#{ENV['LANG']}\nLANGUAGE=#{ENV['LANGUAGE']}\nLC_MESSAGES=#{ENV['LC_MESSAGES']}\n" > /etc/default/locale
+        # set timezone to UTC
+        timedatectl set-timezone "Etc/UTC"
+        
         # keep update service from interfering while installing
         for i in apt-daily.service apt-daily.timer unattended-upgrades.service \
             apt-daily-upgrade.service apt-daily-upgrade.timer ; do
             systemctl disable $i; systemctl stop $i
         done
-        systemctl daemon-reload
-        timedatectl set-timezone "Europe/Vienna"
+
+        # install minimal needed packages
         export DEBIAN_FRONTEND=noninteractive
-        export LC_ALL=#{ENV['LANG']}
-        printf "LANG=#{ENV['LANG']}\nLANGUAGE=#{ENV['LANGUAGE']}\nLC_MESSAGES=#{ENV['LC_MESSAGES']}\n" > /etc/default/locale
         apt-get -y update
         apt-get -y install software-properties-common locales git gosu curl rsync acpid
+        
+        # generate locales
         locale-gen en_US.UTF-8 && dpkg-reconfigure locales
 
+        # set hostname
+        if grep -qa container=lxc /proc/1/environ; then
+            # XXX workaround for lxd, see: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1575779
+            override_dir=/etc/systemd/system/systemd-hostnamed.service.d
+            mkdir -p "$override_dir"
+            echo -n "[Service]\nPrivateNetwork=no\n" > $override_dir/override.conf
+            systemctl daemon-reload
+            systemctl restart systemd-hostnamed
+        fi
+        echo "set hostname to #{settings['servername']}"
+        hostnamectl set-hostname #{settings['servername']}
+        hostname -f || (echo "error $? on hostname -f"; exit 1)
+        
     SHELL
 
     config.vm.provision "shell", privileged:true, inline: <<-SHELL
